### PR TITLE
infix to postfix program

### PR DESCRIPTION
**Pull request by deevya**
A java infix to postfix program for any equation, using stack

### CODE REVIEW

**Comment by codedeliveryguy** [comment]
Hey @deevya make sure your PR follows [Contribution Guidelines](https://github.com/alfaPegasis/dsa-all/blob/main/CONTRIBUTING.md) specified by the maintainer @alfaPegasis

**Comment by deevya** [comment]
> Hey @deevya make sure your PR follows [Contribution Guidelines](https://github.com/alfaPegasis/dsa-all/blob/main/CONTRIBUTING.md) specified by the maintainer @alfaPegasis

What's wrong in this pr? I was unable to understand

**Comment by codedeliveryguy** [comment]
You need to add your code to its specific language folder, currently your code lies in the index folder.

**Review by alfaPegasis — CHANGES_REQUESTED** [review]
Have a look at the contributing guidelines. You have to classify your code accordingly.

**Comment by deevya** [comment]
How can i make the required change

**Comment by codedeliveryguy** [comment]
> How can i make the required change

I am not sure wheather you can make the requested changes for the same PR, what I would suggest you is 

1. Open any online/offline code editor (you can do that be replacing .com with .dev in the repo URL ) or use [this](https://github.dev/deevya/dsa-all) link
2. Move your code to it's respective folder
3. Open a new PR

**Pull request closed without merging**
